###############################################################################
# Global Designer parameters
# https://all.docs.genesys.com/DES/Current/DESPEGuide/Configure
###############################################################################
designer:
  deployment:
    strategy: blue-green-volume
  volumes:
    logsPvc:  # Logs
      create: true 
      mountPath: /designer/logs     
      claimSize: "5Gi"
      storageClass: "csi-standard-rwx"
    workspacePvc: # Workspace
      create: true
      mountPath: /designer/workspace      
      claimSize: "5Gi"
      storageClass: "csi-standard-rwx"
